SRCS := \
	DataStore/GPUAllocator.cpp \
	Game/main.cpp \
	Game/Game.cpp \
	Game/ScaledDeltaTimer.cpp \
	Scene/InGameScene.cpp \
	Scene/SceneManager.cpp \
	Library/GL/UniformBinding.cpp \
	Library/GL/Shader.cpp \
	Library/GL/Init.cpp \
	Library/GL/ShaderStorageBinding.cpp \
	Library/GL/Program.cpp \
	Library/GL/SetUniform.cpp \
	Library/SDL/Init.cpp \
	Library/SDL/Surface.cpp \
	Library/SDL/Window/WindowInfo.cpp \
 	Library/SDL/Window/GLWindow.cpp \
	Library/Logger/Logger.cpp \
	Render/Material/LoadTexture.cpp \
	Render/Material/Param/BlockRangeParam.cpp \
	Render/Model/ModelLoader.cpp \
	Render/Renderer/ObjectRenderer.cpp \
	Render/Renderer/GBuffer.cpp \
	Render/Renderer/LightPass.cpp \
	Render/Scene/Scene.cpp \
	Render/ProgramInterface/ProgramInterface.cpp \
